/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hjy_bsdiff_FileDiffer */

#ifndef _Included_com_hjy_bsdiff_FileDiffer
#define _Included_com_hjy_bsdiff_FileDiffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hjy_bsdiff_FileDiffer
 * Method:    fileDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hjy_bsdiff_FileDiffer_fileDiff
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_hjy_bsdiff_FileDiffer
 * Method:    fileCombine
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
jint JNICALL Java_com_hjy_bsdiff_FileDiffer_fileCombine
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
